[package]
name = "mesh_simulator"
version = "0.1.0"
authors = ["Moritz Warning <moritzwarning@web.de>"]
edition = "2018"

[dependencies]
rand = "0.6.5"
serde_json = "1.0.18"
hyperbolic_graph_generator = "0.1.0"

[profile.release]
debug = true
